service: aws-lambda-calc
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: calc.handler
    events:
      - httpApi:
          path: /
          method: get
